services:
  - type: web
    name: education-ml-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_GEMINI_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false